import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const readexPro = localFont({
  display: 'swap',
  src: [
    {
      path: "./font/ReadexPro-VariableFont_HEXP,wght.ttf",
    },
  ],
  variable: '--font-readex-pro',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${readexPro.variable} antialiased overflow-scroll`}
      >
        {children}
      </body>
    </html>
  );
}
